### ISSUE TITLE
Group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by abiola-arobieke** [abiola-arobieke/js-capstone-project#21]
Kanban url: https://github.com/abiola-arobieke/js-capstone-project/projects/1

We are two people in this group, @emarkees  and @abiola-arobieke

**Comment by victorokoroji** [comment]
Hi @abiola-arobieke, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯


- The issue  title and description are professional and descriptive ✅ 



## Required Changes ♻️

- [ ] Please note that you are in a team of two and as such you are not to assign the tasks specified for student C. KIndly assign tasks for only students A ad  B with one if you as student A and the other as student  B. So you should have 15 cards in total assigned not 20 and the points. Please correct this 👍🏽. 

- [x] Kindly assign both of you to group tasks. I can see that only one person was assigned to group tasks. I should see your two images appear as avatars for group tasks.

_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by levy002** [comment]
## Hello @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
